language: go

go:
  - 1.4

install:
  - go get "github.com/mattn/go-isatty"
  - go get "github.com/shiena/ansicolor"
  - go get "github.com/mattbaird/elastigo"
  - go get "github.com/stretchr/testify/assert"
